--- #YAML:1.0
name:               Chart
version:            2.400.1
abstract:           a series of charting modules
author:
  - 'Chart-Group <chartgrp@web.de>'

license:            Artistic
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    GD:  2
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
resources:
  repository: https://github.com/lichtkind/Chart.git


